# Generated by Django 5.1.2 on 2025-01-16 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_contestthresholdsubmission_contest_contesttag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.contest')),
            ],
        ),
        migrations.CreateModel(
            name='QuizField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveIntegerField(default=6)),
                ('height', models.PositiveIntegerField(default=4)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='QuizFieldCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('cell_type', models.CharField(choices=[('normal', 'Normal'), ('blocked', 'Blocked'), ('special', 'Special')], default='normal', max_length=20)),
                ('quizField', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='myapp.quizfield')),
            ],
        ),
        migrations.CreateModel(
            name='QuizProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('answer', models.CharField(max_length=100)),
                ('points', models.PositiveIntegerField()),
                ('quizFieldCell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.quizfieldcell')),
            ],
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('is_successful', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='myapp.quizproblem')),
            ],
        ),
    ]
