# Generated by Django 5.1.2 on 2025-01-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_quizfieldcell_cell_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizuser',
            name='score',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
