# Generated by Django 5.1.2 on 2025-01-31 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_appconfig_alter_quizfield_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizuser',
            name='combo_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
