# Generated by Django 5.1.2 on 2024-12-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_submissionfile_contestchecker_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='time_end',
            field=models.DateTimeField(default='2024-12-01 10:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contest',
            name='time_start',
            field=models.DateTimeField(default='2024-12-01 12:00:00'),
            preserve_default=False,
        ),
    ]
