# Generated by Django 5.1.2 on 2024-12-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_contestcheckeranswerfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
