# Generated by Django 5.1.2 on 2024-12-03 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_contest_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contest_access',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='myapp.contest', verbose_name='Доступ к соревнованию'),
        ),
    ]
