# Generated by Django 5.1.2 on 2025-01-17 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_quiz_quizfield_quizfieldcell_quizproblem_quizattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizfieldcell',
            name='col',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizfieldcell',
            name='row',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='QuizUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.quiz')),
            ],
        ),
    ]
